### ISSUE TITLE
readme.md

### ISSUE THREAD

**Issue by dcoille** [Bonitasoft-Community/getting-started-fr#3]
this page could be enriched

**Comment by MittchoBaroco** [comment]
I would love to work on this, to be sure, you would like a translation of the original readme into french?

**Comment by swapniljha001** [comment]
Will Google Translate help? Or is that too unreliable for English to French technical translations?

**Comment by Knackie** [comment]
Hi, i'm french, i can help you 👍

**Comment by dcoille** [comment]
Hi guys, that's great if you can help. I have created a first version of this readme in english, feel free to contribute :-)

**Comment by dcoille** [comment]
Needed to finish the file translation quickly
